# #####################################################################
# Automatically generated by qmake (2.01a) Thu Apr 29 16:30:58 2010
# #####################################################################
TEMPLATE = app
#TEMPLATE = lib
win32 { 
    LIBS += -fopenmp
    TARGET = shelxle
    RC_FILE = shelxle.rc
}
!mac{
unix {
TARGET = shelxle
target.path = /usr/bin
INSTALLS += target
data.path = /usr/share/shelxle
data.files = help/*
INSTALLS += data
icon.path = /usr/share/pixmaps
icon.files = shelxle.png
INSTALLS += icon
desktop.path = /usr/share/applications
desktop.files = shelxle.desktop
INSTALLS += desktop
LIBS += -fopenmp -lGLU
#LIBS += -lfftw3f
}}
mac {
LIBS += -fopenmp 
TARGET = shelxle
ICON = macshelx.icns
}
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl
QT += network
QMAKE_CXXFLAGS += -fopenmp
# Input
HEADERS += window.h \
    itsme.h \
    chgl.h \
    highlighter.h \
    molecule.h \
    fcvsfo.h\
    dragdropatomsdlg.h \
    codeeditor.h \
    eacDlg.h \
    shx_helper.h \
    qpeakview.h \
    psewidget.h \
    historywidget.h\
    fourxle.h\
    savehistorywidget.h \
    calculator.h
SOURCES += main.cpp \
    window.cpp \
    molecule.cpp \
    fcvsfo.cpp\
    chgl.cpp \
    highlighter.cpp \
    codeeditor.cpp \
    eacDlg.cpp \
    qpeakview.cpp \
    psewidget.cpp \
    historywidget.cpp \
    dragdropatomsdlg.cpp \
    fourxle.cpp \
    kissfft/kiss_fftnd.c \
    kissfft/kiss_fft.c \
    savehistorywidget.cpp \
    calculator.cpp
RESOURCES += icons.qrc
OTHER_FILES += shelxle.rc
